# Generated by Django 2.2 on 2019-04-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopLlat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('TopLlon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('BotRlat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('BotRlon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('imgUrl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obejkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopLlat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('TopLlon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('BotRlat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('BotRlon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovaAplikacija.Mapa')),
            ],
        ),
    ]
